/*********************************************************************************/
/********** THIS FILE IS GENERATED BY TOUCHGFX DESIGNER, DO NOT MODIFY ***********/
/*********************************************************************************/
#include <gui_generated/screen1_screen/Screen1ViewBase.hpp>
#include <touchgfx/canvas_widget_renderer/CanvasWidgetRenderer.hpp>
#include <touchgfx/Color.hpp>
#include <images/BitmapDatabase.hpp>
#include <texts/TextKeysAndLanguages.hpp>

Screen1ViewBase::Screen1ViewBase()
{
    touchgfx::CanvasWidgetRenderer::setupBuffer(canvasBuffer, CANVAS_BUFFER_SIZE);
    
    __background.setPosition(0, 0, 480, 854);
    __background.setColor(touchgfx::Color::getColorFromRGB(0, 0, 0));
    add(__background);

    scalableImage3_1.setBitmap(touchgfx::Bitmap(BITMAP_BLANK_WHITE_7SN5O1WOONMKLX1H_ID));
    scalableImage3_1.setPosition(0, 0, 480, 854);
    scalableImage3_1.setScalingAlgorithm(touchgfx::ScalableImage::NEAREST_NEIGHBOR);
    add(scalableImage3_1);

    box1.setPosition(5, 73, 471, 50);
    box1.setColor(touchgfx::Color::getColorFromRGB(184, 176, 176));
    add(box1);

    textArea2.setXY(174, 240);
    textArea2.setColor(touchgfx::Color::getColorFromRGB(0, 0, 0));
    textArea2.setLinespacing(0);
    textArea2.setTypedText(touchgfx::TypedText(T___SINGLEUSE_46HA));
    add(textArea2);

    textArea3.setXY(290, 240);
    textArea3.setColor(touchgfx::Color::getColorFromRGB(0, 0, 0));
    textArea3.setLinespacing(0);
    textArea3.setTypedText(touchgfx::TypedText(T___SINGLEUSE_N8FZ));
    add(textArea3);

    textArea5.setXY(357, 240);
    textArea5.setColor(touchgfx::Color::getColorFromRGB(0, 0, 0));
    textArea5.setLinespacing(0);
    textArea5.setTypedText(touchgfx::TypedText(T___SINGLEUSE_QS7G));
    add(textArea5);

    textArea7.setXY(68, 656);
    textArea7.setColor(touchgfx::Color::getColorFromRGB(0, 0, 0));
    textArea7.setLinespacing(0);
    textArea7.setTypedText(touchgfx::TypedText(T___SINGLEUSE_4W8T));
    add(textArea7);

    textArea8.setXY(309, 656);
    textArea8.setColor(touchgfx::Color::getColorFromRGB(0, 0, 0));
    textArea8.setLinespacing(0);
    textArea8.setTypedText(touchgfx::TypedText(T___SINGLEUSE_2KOQ));
    add(textArea8);

    textArea12.setXY(63, 80);
    textArea12.setColor(touchgfx::Color::getColorFromRGB(255, 5, 5));
    textArea12.setLinespacing(0);
    textArea12.setTypedText(touchgfx::TypedText(T___SINGLEUSE_EDI9));
    add(textArea12);

    box2.setPosition(13, 355, 458, 184);
    box2.setColor(touchgfx::Color::getColorFromRGB(224, 139, 139));
    add(box2);

    textArea13.setXY(51, 373);
    textArea13.setColor(touchgfx::Color::getColorFromRGB(0, 0, 0));
    textArea13.setLinespacing(0);
    textArea13.setTypedText(touchgfx::TypedText(T___SINGLEUSE_8F3V));
    add(textArea13);

    textArea14.setXY(370, 460);
    textArea14.setColor(touchgfx::Color::getColorFromRGB(0, 0, 0));
    textArea14.setLinespacing(0);
    textArea14.setTypedText(touchgfx::TypedText(T___SINGLEUSE_GDCB));
    add(textArea14);

    textArea15.setXY(214, 460);
    textArea15.setColor(touchgfx::Color::getColorFromRGB(0, 0, 0));
    textArea15.setLinespacing(0);
    textArea15.setTypedText(touchgfx::TypedText(T___SINGLEUSE_4FRM));
    add(textArea15);

    textArea16.setXY(51, 460);
    textArea16.setColor(touchgfx::Color::getColorFromRGB(0, 0, 0));
    textArea16.setLinespacing(0);
    textArea16.setTypedText(touchgfx::TypedText(T___SINGLEUSE_FTXJ));
    add(textArea16);

    textArea17.setXY(370, 373);
    textArea17.setColor(touchgfx::Color::getColorFromRGB(0, 0, 0));
    textArea17.setLinespacing(0);
    textArea17.setTypedText(touchgfx::TypedText(T___SINGLEUSE_AB59));
    add(textArea17);

    textArea18.setXY(214, 373);
    textArea18.setColor(touchgfx::Color::getColorFromRGB(0, 0, 0));
    textArea18.setLinespacing(0);
    textArea18.setTypedText(touchgfx::TypedText(T___SINGLEUSE_SMLL));
    add(textArea18);

    textArea19.setXY(38, 240);
    textArea19.setColor(touchgfx::Color::getColorFromRGB(0, 0, 0));
    textArea19.setLinespacing(0);
    textArea19.setTypedText(touchgfx::TypedText(T___SINGLEUSE_K3KX));
    add(textArea19);

    circle1.setPosition(221, -9, 81, 78);
    circle1.setCenter(40, 40);
    circle1.setRadius(26);
    circle1.setLineWidth(0);
    circle1.setArc(0, 360);
    circle1Painter.setColor(touchgfx::Color::getColorFromRGB(86, 188, 214));
    circle1.setPainter(circle1Painter);
    circle1.setAlpha(167);
    add(circle1);

    textArea20.setXY(250, 12);
    textArea20.setColor(touchgfx::Color::getColorFromRGB(0, 0, 0));
    textArea20.setLinespacing(0);
    textArea20.setTypedText(touchgfx::TypedText(T___SINGLEUSE_44KF));
    add(textArea20);

    digitalClock1.setPosition(390, 16, 81, 29);
    digitalClock1.setColor(touchgfx::Color::getColorFromRGB(0, 0, 0));
    digitalClock1.setTypedText(touchgfx::TypedText(T___SINGLEUSE_85UD));
    digitalClock1.displayLeadingZeroForHourIndicator(true);
    digitalClock1.setDisplayMode(touchgfx::DigitalClock::DISPLAY_24_HOUR);
    digitalClock1.setTime24Hour(10, 10, 0);
    add(digitalClock1);

    box4.setPosition(167, 791, 151, 50);
    box4.setColor(touchgfx::Color::getColorFromRGB(199, 191, 191));
    add(box4);

    textArea22.setXY(232, 798);
    textArea22.setColor(touchgfx::Color::getColorFromRGB(0, 0, 0));
    textArea22.setLinespacing(0);
    textArea22.setTypedText(touchgfx::TypedText(T___SINGLEUSE_F2SG));
    add(textArea22);

    box5.setPosition(13, 11, 126, 45);
    box5.setColor(touchgfx::Color::getColorFromRGB(173, 170, 170));
    add(box5);

    textArea23.setXY(45, 19);
    textArea23.setColor(touchgfx::Color::getColorFromRGB(0, 0, 0));
    textArea23.setLinespacing(0);
    textArea23.setTypedText(touchgfx::TypedText(T___SINGLEUSE_JXW1));
    add(textArea23);

    box6.setPosition(327, 791, 144, 50);
    box6.setColor(touchgfx::Color::getColorFromRGB(173, 170, 170));
    add(box6);

    box7.setPosition(13, 791, 144, 50);
    box7.setColor(touchgfx::Color::getColorFromRGB(173, 170, 170));
    add(box7);

    textArea24.setXY(382, 798);
    textArea24.setColor(touchgfx::Color::getColorFromRGB(0, 0, 0));
    textArea24.setLinespacing(0);
    textArea24.setTypedText(touchgfx::TypedText(T___SINGLEUSE_ZKF6));
    add(textArea24);

    textArea25.setXY(56, 798);
    textArea25.setColor(touchgfx::Color::getColorFromRGB(0, 0, 0));
    textArea25.setLinespacing(0);
    textArea25.setTypedText(touchgfx::TypedText(T___SINGLEUSE_OYB4));
    add(textArea25);

    line2.setPosition(327, 356, 25, 182);
    line2Painter.setColor(touchgfx::Color::getColorFromRGB(150, 143, 143));
    line2.setPainter(line2Painter);
    line2.setStart(0, 200);
    line2.setEnd(0, 0);
    line2.setLineWidth(5.9f);
    line2.setLineEndingStyle(touchgfx::Line::ROUND_CAP_ENDING);
    add(line2);

    line2_1.setPosition(160, 354, 15, 183);
    line2_1Painter.setColor(touchgfx::Color::getColorFromRGB(150, 143, 143));
    line2_1.setPainter(line2_1Painter);
    line2_1.setStart(0, 200);
    line2_1.setEnd(0, 0);
    line2_1.setLineWidth(5.9f);
    line2_1.setLineEndingStyle(touchgfx::Line::ROUND_CAP_ENDING);
    add(line2_1);

    shape1.setPosition(183, 16, 48, 34);
    shape1.setOrigin(10.0f, 7.0f);
    shape1.setScale(1.1f, 0.9f);
    shape1.setAngle(0.0f);
    shape1Painter.setColor(touchgfx::Color::getColorFromRGB(0, 0, 0));
    shape1.setPainter(shape1Painter);
    const touchgfx::AbstractShape::ShapePoint<float> shape1Points[6] = { { 20.0f, 20.0f }, { 20.0f, 125.0f }, { 20.0f, 30.0f }, { -8.0f, 10.0f }, { 20.0f, -10.0f }, { 20.0f, -120.0f } };
    shape1.setShape(shape1Points);
    add(shape1);

    shape1_1.setPosition(306, 13, 42, 41);
    shape1_1.setOrigin(5.0f, 5.0f);
    shape1_1.setScale(1.3f, 1.0f);
    shape1_1.setAngle(65.0f);
    shape1_1Painter.setColor(touchgfx::Color::getColorFromRGB(0, 0, 0));
    shape1_1.setPainter(shape1_1Painter);
    const touchgfx::AbstractShape::ShapePoint<float> shape1_1Points[6] = { { 20.0f, 20.0f }, { 20.0f, 20.0f }, { 20.0f, 30.0f }, { -8.0f, 10.0f }, { 20.0f, -20.0f }, { 20.0f, -20.0f } };
    shape1_1.setShape(shape1_1Points);
    add(shape1_1);

    textProgress.setXY(-1, 167);
    textProgress.setProgressIndicatorPosition(12, 10, 150, 30);
    textProgress.setRange(0, 100);
    textProgress.setColor(touchgfx::Color::getColorFromRGB(0, 0, 0));
    textProgress.setTypedText(touchgfx::TypedText(T___SINGLEUSE_HTEH));
    textProgress.setBackground(touchgfx::Bitmap(BITMAP_AFEJASEIFJJ_ID));
    textProgress.setValue(0);
    add(textProgress);

    textProgress_2.setXY(252, 579);
    textProgress_2.setProgressIndicatorPosition(12, 10, 150, 30);
    textProgress_2.setRange(0, 100);
    textProgress_2.setColor(touchgfx::Color::getColorFromRGB(0, 0, 0));
    textProgress_2.setTypedText(touchgfx::TypedText(T___SINGLEUSE_HETC));
    textProgress_2.setBackground(touchgfx::Bitmap(BITMAP_AFEJASEIFJJ_ID));
    textProgress_2.setValue(0);
    add(textProgress_2);

    textProgress_3.setXY(65, 579);
    textProgress_3.setProgressIndicatorPosition(12, 10, 150, 30);
    textProgress_3.setRange(0, 100);
    textProgress_3.setColor(touchgfx::Color::getColorFromRGB(0, 0, 0));
    textProgress_3.setTypedText(touchgfx::TypedText(T___SINGLEUSE_D5TY));
    textProgress_3.setBackground(touchgfx::Bitmap(BITMAP_AFEJASEIFJJ_ID));
    textProgress_3.setValue(0);
    add(textProgress_3);

    textProgress_4.setXY(317, 167);
    textProgress_4.setProgressIndicatorPosition(12, 10, 150, 30);
    textProgress_4.setRange(0, 100);
    textProgress_4.setColor(touchgfx::Color::getColorFromRGB(0, 0, 0));
    textProgress_4.setTypedText(touchgfx::TypedText(T___SINGLEUSE_UPUI));
    textProgress_4.setBackground(touchgfx::Bitmap(BITMAP_AFEJASEIFJJ_ID));
    textProgress_4.setValue(0);
    add(textProgress_4);

    textProgress_5.setXY(214, 167);
    textProgress_5.setProgressIndicatorPosition(12, 10, 150, 30);
    textProgress_5.setRange(0, 100);
    textProgress_5.setColor(touchgfx::Color::getColorFromRGB(0, 0, 0));
    textProgress_5.setTypedText(touchgfx::TypedText(T___SINGLEUSE_R4B2));
    textProgress_5.setBackground(touchgfx::Bitmap(BITMAP_AFEJASEIFJJ_ID));
    textProgress_5.setValue(0);
    add(textProgress_5);

    textProgress_6.setXY(115, 167);
    textProgress_6.setProgressIndicatorPosition(12, 10, 150, 30);
    textProgress_6.setRange(0, 100);
    textProgress_6.setColor(touchgfx::Color::getColorFromRGB(0, 0, 0));
    textProgress_6.setTypedText(touchgfx::TypedText(T___SINGLEUSE_NGHV));
    textProgress_6.setBackground(touchgfx::Bitmap(BITMAP_AFEJASEIFJJ_ID));
    textProgress_6.setValue(0);
    add(textProgress_6);
}

Screen1ViewBase::~Screen1ViewBase()
{
    touchgfx::CanvasWidgetRenderer::resetBuffer();
}

void Screen1ViewBase::setupScreen()
{

}

void Screen1ViewBase::handleKeyEvent(uint8_t key)
{
    if(2 == key)
    {
        //Left_Blinker
        //When hardware button 2 clicked change color of shape1
        //Set RGB color R:255, G:255, B:0 on shape1
        shape1Painter.setColor(touchgfx::Color::getColorFromRGB(255, 255, 0));
        shape1.invalidate();
    
    }

    if(3 == key)
    {
        //Right_blinker
        //When hardware button 3 clicked change color of shape1_1
        //Set RGB color R:0, G:0, B:0 on shape1_1
        shape1_1Painter.setColor(touchgfx::Color::getColorFromRGB(0, 0, 0));
        shape1_1.invalidate();
    
    }
}
